# Generated by Django 2.1.7 on 2019-03-25 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('duration', models.TextField(default='1 месяц')),
                ('days_and_time', models.TextField(default='Среда, Пятница с 19:00 до 22:00')),
                ('price', models.IntegerField(default=120000)),
                ('price_show', models.TextField(default='120 000 тенге<br>90 000 тенге при предоплате')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(default='000')),
                ('name', models.TextField(default='Python для анализа данных')),
                ('description', models.TextField(default='С самого нуля вы будете обучаться...')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='python')),
                ('url', models.TextField(default='/static/img/courses/python.svg')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True)),
                ('name', models.TextField(default='ФИО')),
                ('iin', models.TextField(blank=True, max_length=15, null=True)),
                ('phone', models.TextField(blank=True, default='+7', null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Cohort')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True)),
                ('name', models.TextField(default='ФИО')),
                ('phone', models.TextField(blank=True, default='+7', null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tag', models.TextField(default='instagram?')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Image'),
        ),
        migrations.AddField(
            model_name='cohort',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Course'),
        ),
    ]
