# Generated by Django 2.1.7 on 2019-03-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
