# Generated by Django 2.1.7 on 2019-04-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cohort_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='price_show_line2',
            field=models.TextField(default='90 000 тенге при предоплате'),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='price_show',
            field=models.TextField(default='120 000 тенге'),
        ),
    ]
