# Generated by Django 2.1.7 on 2019-04-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190404_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitestat',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
