# Generated by Django 2.1.7 on 2019-04-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190404_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='url',
            field=models.TextField(default='short_url'),
        ),
    ]
